# Generated by Django 2.2.15 on 2020-08-11 01:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=1)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('pic', models.ImageField(default='profile_pics/kisspng-user-avatar-playerunknown-s-battlegrounds-cryptocu-5b090fc8c0a8e4.6350091115273205207892.jpg', upload_to='profile_pics/')),
                ('birth_date', models.DateTimeField()),
                ('city', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
