# Generated by Django 2.2.15 on 2020-08-16 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
