# Generated by Django 2.2.15 on 2020-08-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0003_auto_20200815_0303'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='our-events')),
            ],
        ),
    ]
