# Generated by Django 2.2.15 on 2020-08-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0004_ourevents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurEvents',
            new_name='OurEvent',
        ),
    ]
