# Generated by Django 2.2.15 on 2020-08-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0005_auto_20200815_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='our-clients')),
                ('description', models.TextField()),
            ],
        ),
    ]
