# Generated by Django 2.2.15 on 2020-08-15 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0007_auto_20200815_2008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Vision',
        ),
    ]
