# Generated by Django 2.2.15 on 2020-08-17 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0008_auto_20200815_2050'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OurEvent',
        ),
    ]
