# Generated by Django 2.2.15 on 2020-08-08 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import invitation_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('image', models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path)),
                ('image_state', models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path)),
                ('barcode', models.UUIDField(null=True)),
                ('svg', models.FileField(upload_to=invitation_app.models.event_directory_path)),
                ('is_state_update', models.BooleanField(default=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(editable=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads/')),
                ('event_image', models.FileField(upload_to='uploads/')),
                ('template_name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.UUIDField(unique=True)),
                ('guest_name', models.CharField(blank=True, max_length=200, null=True)),
                ('svg', models.FileField(upload_to=invitation_app.models.event_directory_path_for_guest_svg)),
                ('image', models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path_for_guest_image)),
                ('state', models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path_for_guest_state)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_app.Event')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invitation_app.Country')),
            ],
        ),
    ]
