# Generated by Django 2.2.15 on 2020-08-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_type',
            name='img',
            field=models.ImageField(default=1, upload_to='our-events'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event_type',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
