# Generated by Django 2.2.15 on 2020-08-18 17:16

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0002_auto_20200817_2157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image_state',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_state_update',
        ),
        migrations.RemoveField(
            model_name='event',
            name='svg',
        ),
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invitation_app.Event_Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(max_length=100),
        ),
    ]
