# Generated by Django 2.2.15 on 2020-08-18 18:06

from django.db import migrations, models
import invitation_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0003_auto_20200818_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='barcode',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path),
        ),
        migrations.AddField(
            model_name='event',
            name='image_state',
            field=models.FileField(blank=True, null=True, storage=invitation_app.models.OverwriteStorage(), upload_to=invitation_app.models.event_directory_path),
        ),
        migrations.AddField(
            model_name='event',
            name='is_state_update',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event',
            name='svg',
            field=models.FileField(default=1, upload_to=invitation_app.models.event_directory_path),
            preserve_default=False,
        ),
    ]
