# Generated by Django 2.2.15 on 2020-09-13 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitation_app', '0004_auto_20200818_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templates',
            options={'verbose_name_plural': 'Templates'},
        ),
    ]
